### ISSUE TITLE
Todo intializing error

### ISSUE THREAD

**Issue by diegoflorez** [stefanoverna/redpomo#3]
running redpomo, i get this:

``` ruby
  \home/diego/.gem/ruby/2.2.0/gems/todo-txt-0.4/lib/todo-txt/task.rb:6:in `<class:Task>': uninitialized constant Todo::Logger (NameError)
    from /home/diego/.gem/ruby/2.2.0/gems/todo-txt-0.4/lib/todo-txt/task.rb:4:in `<module:Todo>'
    from /home/diego/.gem/ruby/2.2.0/gems/todo-txt-0.4/lib/todo-txt/task.rb:3:in `<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/diego/.gem/ruby/2.2.0/gems/redpomo-0.0.13/lib/redpomo/task.rb:2:in `<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/diego/.gem/ruby/2.2.0/gems/redpomo-0.0.13/lib/redpomo/task_list.rb:2:in `<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/diego/.gem/ruby/2.2.0/gems/redpomo-0.0.13/lib/redpomo/cli.rb:5:in `<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
    from /home/diego/.gem/ruby/2.2.0/gems/redpomo-0.0.13/bin/redpomo:4:in `<top (required)>'
    from /home/diego/.gem/ruby/2.2.0/bin/redpomo:23:in `load'
    from /home/diego/.gem/ruby/2.2.0/bin/redpomo:23:in `<main>'
```

**Comment by iaminawe** [comment]
I get this error too
